services:
  react-todo-list-localstorage:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: react-todo-list-localstorage
    ports:
      - "8000:8000" 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev